[package]
name = "RepoGuardian"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
walkdir = "2.5.0"
chrono = { version = "0.4.42", features = ["serde"] }
ratatui = "0.30.0"
crossterm = "0.29.0"
clearscreen = "4.0.2"
dirs = "6.0.0"
dircpy = "0.3.19"
serde_json = "1.0.149"
lazy_static = "1.5.0"
uuid = { version = "1.19.0", features = ["v4"] }
ctrlc = "3.5.1"
colored_text = "0.3.0"
#tiny-gradient = "0.1.0"
tinterm = "0.2.0"

[[bin]]
name = "repoguardian"
path = "src/main.rs"

[[bin]]
name = "repoguardian-tui"
path = "src/tui_main.rs"
